version: '3'
services:
  rhizomer:
    image: rhizomik/rhizomer-eye
    container_name: rhizomer
    ports:
      - "80:80"
    environment:
      - API_URL=${API_URL:-http://localhost:8080}
  rhizomer-api:
    image: rhizomik/rhizomer-api
    container_name: rhizomer-api
    ports:
      - "8080:8080"
    environment:
      - ALLOWED_ORIGINS=${CLIENT_URL:-http://localhost}
      - RHIZOMER_DEFAULT_PASSWORD=password
